### ISSUE TITLE
location for "lb datasource command"

### ISSUE THREAD

**Issue by szihai** [IBM/loopback-in-five#5]
In the read.me, it says "Next, from the same directory as step 1". Actually after creating the app, we are supposed to "cd _appname_". Otherwise there will be an error.

**Comment by dokun1** [comment]
This is actually technically correct, assuming you did step 1 in an empty directory that you named `AnimalsDemo` like in the dialog. If you type the name of a new directory, then yes, you have to `cd` into it.

Which do you think would be better to demonstrate? I could go either way. FWIW, I always make a new directory and start inside that directory from scratch.

**Comment by szihai** [comment]
yes, you are right that if I used AnimalsDemo it will work. However the confusing part is : a. there is no mentioning of the app name is "fixed" and b. After creating the app, the lb will prompt to cd to that folder. I'm leaning towards doing the cd and giving user the freedom to choose the app name.

**Comment by dokun1** [comment]
Ok, so I'll tell them to write the name of the folder they want to use, but that they can choose to use the current folder that they're in, and default behavior takes over. I'll append both steps for this.

**Comment by szihai** [comment]
Thanks, I think the change looks good.
